import numpy as np
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List
import xarray as xr
from fastapi import File, UploadFile
from fastapi.responses import StreamingResponse
from fastapi import Query
import pandas as pd
import io
import tempfile
import os
from fastapi.middleware.cors import CORSMiddleware



# Initialize FastAPI app
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Or specify your frontend domain instead of "*"
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load GEBCO dataset once
bathymetry = xr.open_dataset("GEBCO_2024.nc")

# --- Utility function ---
def get_depth(lat, lon):
    """Find nearest depth value from the dataset."""
    depth = bathymetry['elevation'].sel(lat=lat, lon=lon, method="nearest").values.item()
    return depth

# --- API Endpoints ---

@app.get("/ping")
def ping():
    """Health check endpoint."""
    return {"status": "ok"}

@app.get("/depth")
def read_depth(lat: float, lon: float):
    """Get depth for a single latitude and longitude."""
    try:
        if not (-90 <= lat <= 90):
            raise HTTPException(status_code=400, detail="Latitude must be between -90 and 90.")
        if not (-180 <= lon <= 180):
            raise HTTPException(status_code=400, detail="Longitude must be between -180 and 180.")
        
        depth = get_depth(lat, lon)
        return {"latitude": lat, "longitude": lon, "depth_meters": depth}
    
    except Exception as e:
        return {"error": str(e)}

# Batch request model
class Location(BaseModel):
    lat: float
    lon: float

@app.post("/batch_depths")
def batch_depths(locations: List[Location]):
    """Get depths for multiple locations."""
    results = []
    for loc in locations:
        try:
            if not (-90 <= loc.lat <= 90) or not (-180 <= loc.lon <= 180):
                results.append({
                    "latitude": loc.lat,
                    "longitude": loc.lon,
                    "error": "Invalid latitude or longitude."
                })
                continue
            
            depth = get_depth(loc.lat, loc.lon)
            results.append({
                "latitude": loc.lat,
                "longitude": loc.lon,
                "depth_meters": depth
            })
        except Exception as e:
            results.append({
                "latitude": loc.lat,
                "longitude": loc.lon,
                "error": str(e)
            })
    return results

# Mount static folder
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
def read_root():
    """Serve the frontend page."""
    return FileResponse("static/index.html")

@app.post("/upload_csv")
async def upload_csv(file: UploadFile = File(...)):
    # Check if it's a CSV file
    if not file.filename.endswith('.csv'):
        return {"error": "Only CSV files are supported."}
    
    # Read CSV content into pandas DataFrame
    contents = await file.read()
    df = pd.read_csv(io.StringIO(contents.decode('utf-8')))
    
    # Check required columns
    if not all(col in df.columns for col in ["lat", "lon"]):
        return {"error": "CSV must contain 'lat' and 'lon' columns."}
    
    # Compute depths
    df["depth"] = df.apply(lambda row: get_depth(row["lat"], row["lon"]), axis=1)

    # Create CSV response in-memory
    output = io.StringIO()
    df.to_csv(output, index=False)
    output.seek(0)

    return StreamingResponse(output, media_type="text/csv", headers={
        "Content-Disposition": "attachment; filename=depth_results.csv"
    })

@app.get("/area_depths_netcdf")
def get_area_depths_netcdf(
    min_lat: float = Query(...),
    max_lat: float = Query(...),
    min_lon: float = Query(...),
    max_lon: float = Query(...),
    step: float = Query(0.1)
):
    if min_lat > max_lat or min_lon > max_lon:
        return {"error": "Minimum values must be less than maximum values."}
    if step <= 0:
        return {"error": "Step must be positive."}

    # Generate lat/lon grid
    lats = np.arange(min_lat, max_lat + step, step)
    lons = np.arange(min_lon, max_lon + step, step)
    lat_grid, lon_grid = np.meshgrid(lats, lons, indexing='ij')

    # Fetch depths
    depths = np.array([[get_depth(lat, lon) for lon in lons] for lat in lats])

    # Create xarray Dataset
    ds = xr.Dataset(
        {
            "elevation": (["lat", "lon"], depths)
        },
        coords={
            "lat": lats,
            "lon": lons
        },
        attrs={
            "title": "GEBCO Water Depth Subset",
            "source": "Generated by FastAPI Server",
            "creator": "Kumars Mahmoodi",
            "email": "kumarsmahmoodi@yahoo.com",
            "page": "https://www.linkedin.com/in/kumars-mahmoodi-17976a150/"
        }
    )

    # Write to temporary NetCDF file
    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".nc")
    ds.to_netcdf(tmp_file.name)
    tmp_file.close()

    return FileResponse(
        tmp_file.name,
        media_type="application/x-netcdf",
        filename="area_depths.nc"
    )

if __name__ == "__main__":
    import uvicorn
    import os
    port = int(os.environ.get("PORT", 8080))  # Cloud Run expects this
    uvicorn.run("main:app", host="0.0.0.0", port=port)
